#!/bin/bash

### PI, TP, log
# 2 m, 151 MHz
# 21 cm, 1,4 GHz
# 20 cm, 1,5 GHz
# 6 cm, 5 GHz
# 3cm, 10 GHz
python3 ./main.py -f ${FILE}.h5 -x -l 0.21 -v -pt --log
python3 ./main.py -f ${FILE}.h5 -z -l 0.21 -v -pt --log

### Faraday Rotation, linear
python3 ./main.py -f ${FILE}.h5 -x -r
python3 ./main.py -f ${FILE}.h5 -z -r

exit
